server:
  port: 8888

spring:
  application:
    name: config-service
  profiles:
    active: native
  cloud:
    config:
      server:
        native:
          search-locations: file://${user.home}/JiksGit/Work
        git:
#          uri: file://Users/yanghyunjik/JiksGit/Work
          uri: https://github.com/JiksGit/spring-cloud-config.git
#          username: [your username]
#          password: [your password]